# Generated by Django 5.2.3 on 2026-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image_url'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='stock_reserved_quantity_lte_quantity'),
        ),
    ]
