# Generated by Django 5.2.3 on 2026-07-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_formula_item_itemgroup_itemtype_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('id',)},
        ),
    ]
