# Generated by Django 5.2.3 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationrequest",
            name="request_type",
            field=models.CharField(
                choices=[("VACATION", "Vacaciones"), ("PERMISSION", "Permiso")],
                default="VACATION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="is_full_day",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
