# Generated by Django 5.2.3 on 2026-07-06 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_alter_vacationrequestapprovalstep_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, upload_to='employees/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'))]),
        ),
    ]
