# Generated by Django 5.2.3 on 2026-07-17 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequestapprovalstep',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='hr/requests/signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
    ]
