# Generated by Django 5.2.3 on 2026-07-21 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_vacationrequestapprovalstep_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours_count', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_shifts', to='human_resources.vacationrequest')),
            ],
            options={
                'ordering': ('date', 'start_time'),
                'abstract': False,
            },
        ),
    ]
