# Generated by Codex on 2026-07-28

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, model._meta.db_table
                )
            }
        if field.column in columns:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0012_merge_20260721_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("PERMISSION", "Permiso"),
                    ("OVERTIME", "Horas extras"),
                    ("LEAVE", "Licencia"),
                    ("INCAPACITY", "Incapacidad"),
                    ("VACATION", "Vacaciones"),
                    ("LOAN", "Préstamo"),
                    ("OTHER", "Otro"),
                ],
                default="VACATION",
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_requester_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_requester_document",
            field=models.CharField(blank=True, max_length=50),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_position",
            field=models.CharField(blank=True, max_length=120),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_concept",
            field=models.CharField(blank=True, max_length=255),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_frequency",
            field=models.CharField(
                blank=True,
                choices=[("BIWEEKLY", "Quincenal"), ("MONTHLY", "Mensual")],
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_installments_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_expense_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        AddFieldIfNotExists(
            model_name="vacationrequest",
            name="loan_requester_signature",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="hr/loans/signatures/",
                validators=[FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
            ),
        ),
    ]
