# Generated by Codex on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0013_loan_request_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationrequest",
            name="is_remunerated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="remuneration_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="remuneration_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_remuneration_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
