# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0014_vacationrequest_remuneration"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationrequest",
            name="hr_is_remunerated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacationrequest",
            name="admin_is_remunerated",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
