# Generated by Codex on 2026-07-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0015_hr_admin_remuneration_split"),
    ]

    operations = [
        # Simplificación: la decisión de "remunerado" queda exclusivamente en
        # manos del Administrador (no hay opinión separada de RRHH ni prioridad
        # entre ambos). Estos dos campos se agregaron en la migración 0015 pero
        # nunca llegaron a usarse con datos reales, así que se retiran sin
        # afectar `is_remunerated` ni ningún otro dato ya guardado.
        migrations.RemoveField(
            model_name="vacationrequest",
            name="hr_is_remunerated",
        ),
        migrations.RemoveField(
            model_name="vacationrequest",
            name="admin_is_remunerated",
        ),
    ]
