# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0016_simplify_remuneration_admin_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationrequest",
            name="loan_approved_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
