# Generated by Codex on 2026-07-29

from django.db import migrations


def finalize_treasury_approved_loans(apps, schema_editor):
    VacationRequest = apps.get_model("human_resources", "VacationRequest")

    loans = VacationRequest.objects.filter(
        request_type="LOAN",
        status="PENDING_ADMIN",
        hr_decision="APPROVED",
        admin_decision="",
    )
    for loan in loans:
        loan.status = "APPROVED"
        if loan.hr_decided_by_id:
            loan.reviewed_by_id = loan.hr_decided_by_id
        if loan.hr_decided_at:
            loan.reviewed_at = loan.hr_decided_at
        loan.save(update_fields=("status", "reviewed_by", "reviewed_at", "updated_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("human_resources", "0017_loan_approved_amount"),
    ]

    operations = [
        migrations.RunPython(finalize_treasury_approved_loans, migrations.RunPython.noop),
    ]
