# Generated by Codex on 2026-07-31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_finalize_treasury_approved_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('FIXED', 'Fecha fija'), ('FIXED_MOVED_TO_MONDAY', 'Fecha fija trasladada al lunes (Ley Emiliani)'), ('EASTER_BASED', 'Basado en Semana Santa')], max_length=30)),
                ('civil_date', models.DateField()),
                ('original_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('civil_date',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(fields=('year', 'civil_date'), name='unique_public_holiday_per_date'),
        ),
    ]
