# Generated by Codex on 2026-07-31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0019_public_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLegalParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('minimum_wage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transport_allowance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_allowance_salary_cap_factor', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('health_employee_pct', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('pension_employee_pct', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('monthly_hours_divisor_default', models.DecimalField(decimal_places=2, default=230, max_digits=6)),
            ],
            options={
                'ordering': ('-year',),
                'abstract': False,
            },
        ),
    ]
