# Generated by Codex on 2026-07-31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0009_employee_signature_updated_at'),
        ('human_resources', '0020_payroll_legal_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employee')),
            ],
            options={
                'ordering': ('-start_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkScheduleDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('expected_start_time', models.TimeField()),
                ('expected_end_time', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='human_resources.employeeworkschedule')),
            ],
            options={
                'ordering': ('weekday', 'slot'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='employeeworkscheduleday',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday', 'slot'), name='unique_schedule_weekday_slot'),
        ),
    ]
