# Generated by Codex on 2026-07-31

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0009_employee_signature_updated_at'),
        ('human_resources', '0021_employee_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeBiometricId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('biometric_code', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='human_resources.biometricdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_ids', to='employees.employee')),
            ],
            options={
                'ordering': ('employee', '-valid_from'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiometricImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(upload_to='hr/biometric/imports/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Falló')], default='PROCESSING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('unmatched_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='human_resources.biometricdevice')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawBiometricPunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('biometric_code', models.CharField(max_length=30)),
                ('punched_at', models.DateTimeField()),
                ('raw_col3', models.CharField(blank=True, max_length=50)),
                ('raw_col4', models.CharField(blank=True, max_length=50)),
                ('raw_col5', models.CharField(blank=True, max_length=50)),
                ('raw_col6', models.CharField(blank=True, max_length=50)),
                ('raw_line', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_punches', to='human_resources.biometricdevice')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='human_resources.rawbiometricpunch')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='human_resources.biometricimportbatch')),
                ('matched_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_biometric_punches', to='employees.employee')),
            ],
            options={
                'ordering': ('matched_employee', 'punched_at'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='rawbiometricpunch',
            index=models.Index(fields=('matched_employee', 'punched_at'), name='hr_raw_punch_emp_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeebiometricid',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('deleted_at__isnull', True)), fields=('device', 'biometric_code'), name='unique_active_biometric_code_per_device'),
        ),
    ]
