# Generated by Codex on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0022_biometric_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(
                choices=[
                    ('MANUAL', 'Registro manual (check-in/out)'),
                    ('BIOMETRIC', 'Importado del biométrico'),
                    ('MANUAL_CORRECTION', 'Corregido manualmente por RRHH'),
                ],
                default='MANUAL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='raw_punches',
            field=models.ManyToManyField(blank=True, related_name='attendances', to='human_resources.rawbiometricpunch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_manually_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='has_incomplete_marks',
            field=models.BooleanField(default=False),
        ),
    ]
