# Generated by Codex on 2026-07-31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0023_attendance_biometric_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('label', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CALCULATED', 'Calculado'), ('APPROVED', 'Aprobado'), ('PAID', 'Pagado'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_start',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_payroll_period_range'),
        ),
    ]
