# Generated by Codex on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0024_payroll_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='human_resources.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payslip_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='worked_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ordinary_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='health_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pension_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='signature',
            field=models.FileField(blank=True, upload_to='hr/payroll/signatures/', validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='source',
            field=models.CharField(
                choices=[
                    ('MANUAL', 'Manual'),
                    ('ATTENDANCE', 'Cálculo de asistencia/horas'),
                    ('VACATION_REQUEST', 'Solicitud (vacaciones/incapacidad/permiso)'),
                    ('LOAN_INSTALLMENT', 'Cuota de préstamo'),
                    ('SYSTEM', 'Concepto legal calculado (salud, pensión, aux. transporte)'),
                ],
                default='MANUAL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='source_vacation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='human_resources.vacationrequest'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='concept_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
