# Generated by Codex on 2026-07-31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0025_payroll_extend_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleTemplateDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('expected_start_time', models.TimeField()),
                ('expected_end_time', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='human_resources.workscheduletemplate')),
            ],
            options={
                'ordering': ('weekday', 'slot'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='workscheduletemplateday',
            constraint=models.UniqueConstraint(fields=('template', 'weekday', 'slot'), name='unique_template_weekday_slot'),
        ),
        migrations.AddField(
            model_name='employeeworkschedule',
            name='source_template',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='applied_schedules', to='human_resources.workscheduletemplate',
            ),
        ),
    ]
