# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0026_work_schedule_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolllegalparameter',
            name='night_ordinary_surcharge_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='payrolllegalparameter',
            name='day_extra_surcharge_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='payrolllegalparameter',
            name='night_extra_surcharge_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='payrolllegalparameter',
            name='sunday_holiday_surcharge_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
