# Generated by Codex on 2026-07-31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0027_payroll_legal_parameter_surcharge_pcts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceIntelligenceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duplicate_punch_window_minutes', models.PositiveIntegerField(
                    default=15,
                    help_text='Marcaciones del mismo empleado separadas por menos de este tiempo se consideran '
                              'el mismo evento repetido por error (ej. marcó, creyó que falló, volvió a marcar) '
                              'y se colapsan en una sola en vez de contarse como entrada+salida real.',
                )),
                ('schedule_proximity_minutes', models.PositiveIntegerField(
                    default=120,
                    help_text='Al inferir qué marcación es entrada y cuál es salida en un día con marcaciones '
                              "atípicas (1, 3, 5+), se prioriza la que caiga dentro de esta cercanía al horario "
                              "esperado del empleado, en vez de asumir ciegamente 'antes/después de mediodía'.",
                )),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Configuración de inteligencia de asistencia',
                'verbose_name_plural': 'Configuraciones de inteligencia de asistencia',
                'abstract': False,
            },
        ),
    ]
