# Generated by Codex on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0028_attendance_intelligence_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='requested_work_schedule_template',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='schedule_change_requests', to='human_resources.workscheduletemplate',
            ),
        ),
    ]
