# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0029_vacation_request_schedule_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("PERMISSION", "Permiso"),
                    ("OVERTIME", "Horas extras"),
                    ("LEAVE", "Licencia"),
                    ("INCAPACITY", "Incapacidad"),
                    ("VACATION", "Vacaciones"),
                    ("LOAN", "Préstamo"),
                    ("SCHEDULE_CHANGE", "Cambio de horario empleado"),
                    ("OTHER", "Otro"),
                ],
                default="VACATION",
                max_length=20,
            ),
        ),
    ]
