# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0030_schedule_change_request_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE human_resources_vacationrequest "
                        "ADD COLUMN IF NOT EXISTS requested_work_schedule_days "
                        "jsonb NOT NULL DEFAULT '[]'::jsonb"
                    ),
                    reverse_sql=(
                        "ALTER TABLE human_resources_vacationrequest "
                        "DROP COLUMN IF EXISTS requested_work_schedule_days"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="vacationrequest",
                    name="requested_work_schedule_days",
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
    ]
