# Generated by Django 5.2.3 on 2026-08-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_signature_updated_at'),
        ('human_resources', '0031_requested_work_schedule_days'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeebiometricid',
            name='unique_active_biometric_code_per_device',
        ),
        migrations.RenameIndex(
            model_name='rawbiometricpunch',
            new_name='human_resou_matched_420df5_idx',
            old_name='hr_raw_punch_emp_time_idx',
        ),
        migrations.AddConstraint(
            model_name='employeebiometricid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('device', 'biometric_code'), name='unique_active_biometric_code_per_device'),
        ),
    ]
