# Generated by Django 5.2.3 on 2026-06-25 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customer_purchase_mode_wholesale_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('order_confirmed', 'Pedido confirmado'), ('order_shipped', 'Pedido en camino'), ('order_delivered', 'Pedido entregado'), ('order_cancelled', 'Pedido cancelado'), ('wholesale_activated', 'Plan mayorista activado'), ('promo', 'Promoción'), ('info', 'Información')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['customer', '-created_at'], name='notificatio_custome_5fbd22_idx'), models.Index(fields=['customer', 'read'], name='notificatio_custome_318d54_idx')],
            },
        ),
    ]
