# Generated by Django 5.2.3 on 2026-07-21 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_access_password'),
        ('human_resources', '0011_remove_hrnotification_state'),
        ('manufacturing', '0004_area_production_line_catalog'),
        ('notifications', '0002_notification_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StaffNotification',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                        ('module', models.CharField(db_index=True, default='human_resources', max_length=40)),
                        ('notification_type', models.CharField(choices=[('DOCUMENT_EXPIRED', 'Documento vencido'), ('DOCUMENT_EXPIRING', 'Documento por vencer'), ('MISSING_DOCUMENT', 'Documento pendiente'), ('BATCH_ASSIGNED', 'Orden asignada'), ('DISPENSING_PENDING', 'Dispensación pendiente'), ('VERIFICATION_PENDING', 'Verificación pendiente'), ('OUT_OF_SPECIFICATION', 'Resultado fuera de especificación'), ('DOCUMENT_REJECTED', 'Documento rechazado'), ('SIGNATURE_PENDING', 'Firma pendiente'), ('LINE_CLEARANCE_REJECTED', 'Despeje no conforme'), ('RAW_MATERIAL_OUT_OF_TOLERANCE', 'Materia prima fuera de tolerancia'), ('CERTIFICATE_PENDING', 'Certificado de análisis pendiente'), ('MICROBIOLOGY_APPROVED', 'Microbiología aprobada'), ('MICROBIOLOGY_REJECTED', 'Microbiología rechazada'), ('DOSSIER_INCOMPLETE', 'Expediente incompleto'), ('BATCH_READY_FOR_RELEASE', 'Lote listo para liberación'), ('BATCH_RELEASED', 'Lote liberado'), ('BATCH_REJECTED', 'Lote rechazado'), ('GENERAL', 'General')], max_length=40)),
                        ('title', models.CharField(max_length=180)),
                        ('message', models.TextField()),
                        ('due_date', models.DateField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('UNREAD', 'Sin leer'), ('READ', 'Leída'), ('DISMISSED', 'Descartada')], default='UNREAD', max_length=20)),
                        ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='manufacturing.batch')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_notifications', to=settings.AUTH_USER_MODEL)),
                        ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='human_resources.employeedocument')),
                        ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='employees.employee')),
                    ],
                    options={
                        'ordering': ('-created_at',),
                        'abstract': False,
                        'indexes': [models.Index(fields=['employee', '-created_at'], name='notificatio_employe_cfb017_idx'), models.Index(fields=['employee', 'status'], name='notificatio_employe_1ed093_idx')],
                    },
                ),
            ],
            database_operations=[
                # Renombra la tabla física en vez de crear una nueva: preserva los
                # registros de HRNotification ya cargados (vencimientos de documentos).
                migrations.RunSQL(
                    sql="ALTER TABLE human_resources_hrnotification RENAME TO notifications_staffnotification;",
                    reverse_sql="ALTER TABLE notifications_staffnotification RENAME TO human_resources_hrnotification;",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE notifications_staffnotification "
                        "ADD COLUMN module varchar(40) NOT NULL DEFAULT 'human_resources', "
                        "ADD COLUMN batch_id uuid NULL "
                        "REFERENCES manufacturing_batch(id) DEFERRABLE INITIALLY DEFERRED; "
                        "ALTER TABLE notifications_staffnotification ALTER COLUMN notification_type TYPE varchar(40); "
                        "CREATE INDEX notifications_staffnotification_batch_id_idx "
                        "ON notifications_staffnotification (batch_id); "
                        "CREATE INDEX notificatio_employe_cfb017_idx "
                        "ON notifications_staffnotification (employee_id, created_at DESC); "
                        "CREATE INDEX notificatio_employe_1ed093_idx "
                        "ON notifications_staffnotification (employee_id, status);"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS notificatio_employe_1ed093_idx; "
                        "DROP INDEX IF EXISTS notificatio_employe_cfb017_idx; "
                        "DROP INDEX IF EXISTS notifications_staffnotification_batch_id_idx; "
                        "ALTER TABLE notifications_staffnotification "
                        "ALTER COLUMN notification_type TYPE varchar(30), "
                        "DROP COLUMN batch_id, "
                        "DROP COLUMN module;"
                    ),
                ),
            ],
        ),
    ]
