# Generated by Django 5.2.3 on 2026-07-17 00:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_formula_item_itemgroup_itemtype_supplier_and_more"),
        ("employees", "0007_employee_signature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("SCHEDULED", "Programada"),
                            ("PENDING_DISPENSING", "Pendiente de dispensación"),
                            ("DISPENSING", "En dispensación"),
                            ("DISPENSING_DONE", "Dispensación completada"),
                            ("MANUFACTURING", "En fabricación"),
                            ("BULK_PENDING_ANALYSIS", "Producto a granel pendiente de análisis"),
                            ("BULK_APPROVED", "Producto a granel aprobado"),
                            ("FILLING", "En llenado"),
                            ("PACKAGING", "En acondicionamiento"),
                            ("FINISHED_QUARANTINE", "Producto terminado en cuarentena"),
                            ("PENDING_DOCUMENTS", "Pendiente de documentos"),
                            ("PENDING_MICROBIOLOGY", "Pendiente de microbiología"),
                            ("RELEASED", "Liberada"),
                            ("REJECTED", "Rechazada"),
                            ("CLOSED", "Cerrada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=120)),
                ("production_line", models.CharField(blank=True, max_length=120)),
                ("scheduled_at", models.DateField(blank=True, null=True)),
                ("actual_start_at", models.DateTimeField(blank=True, null=True)),
                ("actual_end_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches_as_production_manager",
                        to="employees.employee",
                    ),
                ),
                (
                    "quality_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches_as_quality_manager",
                        to="employees.employee",
                    ),
                ),
                (
                    "production_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch",
                        to="inventory.productionorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BatchStatusHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("previous_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("observation", models.TextField(blank=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="manufacturing/batch-status-evidence/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="manufacturing.batch",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name_plural": "batch status histories",
                "abstract": False,
            },
        ),
    ]
