# Generated by Django 5.2.3 on 2026-07-17 00:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0001_initial"),
        ("inventory", "0004_alter_stock_options"),
        ("employees", "0007_employee_signature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterialBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("supplier_batch_code", models.CharField(max_length=80)),
                ("received_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("analysis_number", models.CharField(blank=True, max_length=80)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[("QUARANTINE", "Cuarentena"), ("APPROVED", "Aprobado"), ("REJECTED", "Rechazado")],
                        default="QUARANTINE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="raw_material_batches", to="inventory.item")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="raw_material_batches", to="inventory.supplier"
                    ),
                ),
            ],
            options={"ordering": ("-received_at", "-created_at"), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="rawmaterialbatch",
            constraint=models.UniqueConstraint(fields=("item", "supplier_batch_code"), name="unique_raw_material_batch_per_item"),
        ),
        migrations.CreateModel(
            name="ItemStock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("reserved_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="inventory.item")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="item_stocks", to="inventory.location")),
                (
                    "raw_material_batch",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="manufacturing.rawmaterialbatch"
                    ),
                ),
            ],
            options={"ordering": ("id",), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="itemstock",
            constraint=models.UniqueConstraint(fields=("item", "location", "raw_material_batch"), name="unique_item_stock_per_location_batch"),
        ),
        migrations.AddConstraint(
            model_name="itemstock",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gte", 0)), name="item_stock_quantity_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="itemstock",
            constraint=models.CheckConstraint(condition=models.Q(("reserved_quantity__gte", 0)), name="item_stock_reserved_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="itemstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("quantity"))), name="item_stock_reserved_lte_quantity"
            ),
        ),
        migrations.CreateModel(
            name="ItemStockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entrada"),
                            ("EXIT", "Salida"),
                            ("DISPENSING", "Dispensación"),
                            ("RETURN", "Devolución"),
                            ("LOSS", "Merma"),
                            ("ADJUSTMENT_IN", "Ajuste positivo"),
                            ("ADJUSTMENT_OUT", "Ajuste negativo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="item_stock_movements", to=settings.AUTH_USER_MODEL),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="inventory.item")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="item_movements", to="inventory.location")),
                (
                    "raw_material_batch",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="manufacturing.rawmaterialbatch"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="DispensingOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendiente"), ("IN_PROGRESS", "En proceso"), ("COMPLETED", "Completada")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateField(blank=True, null=True)),
                (
                    "responsible_signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/dispensing/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                (
                    "verifier_signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/dispensing/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dispensing_order", to="manufacturing.batch")),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_orders_as_responsible", to="employees.employee"
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_orders_as_verifier", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="DispensingLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("theoretical_quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("tolerance_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("tare", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("gross_weight", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("net_weight", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("container", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendiente"), ("WEIGHED", "Pesado"), ("VERIFIED", "Verificado"), ("CLOSED", "Cerrado")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("weighed_at", models.DateTimeField(blank=True, null=True)),
                ("additional_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                ("returned_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("return_reason", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="manufacturing.dispensingorder")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="dispensing_lines", to="inventory.item")),
                (
                    "formula_line",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dispensing_lines", to="inventory.formulaline"
                    ),
                ),
                (
                    "raw_material_batch",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dispensing_lines", to="manufacturing.rawmaterialbatch"
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_lines_weighed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_lines_verified", to="employees.employee"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_lines_added", to="employees.employee"
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dispensing_lines_received", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("sequence", "created_at"), "abstract": False},
        ),
        migrations.CreateModel(
            name="RawMaterialIdentificationPrint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("printed_at", models.DateTimeField(auto_now_add=True)),
                ("is_reprint", models.BooleanField(default=False)),
                ("reprint_reason", models.CharField(blank=True, max_length=255)),
                ("dispensing_line", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="identification_prints", to="manufacturing.dispensingline")),
                ("printed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-printed_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="ManufacturingStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("phase", models.CharField(blank=True, max_length=120)),
                ("instruction", models.TextField()),
                ("required_equipment", models.CharField(blank=True, max_length=120)),
                ("target_temperature", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("target_time_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("target_agitation_speed", models.CharField(blank=True, max_length=60)),
                ("target_ph", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("target_pressure", models.CharField(blank=True, max_length=60)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("formula", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manufacturing_steps", to="inventory.formula")),
                (
                    "formula_line",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manufacturing_steps", to="inventory.formulaline"
                    ),
                ),
            ],
            options={"ordering": ("formula", "sequence"), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="manufacturingstep",
            constraint=models.UniqueConstraint(fields=("formula", "sequence"), name="unique_manufacturing_step_sequence"),
        ),
        migrations.CreateModel(
            name="ManufacturingStepExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En proceso"),
                            ("PAUSED", "Pausado"),
                            ("COMPLETED", "Completado"),
                            ("DEVIATED", "Con desviación"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("actual_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("actual_temperature", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("actual_time_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_agitation_speed", models.CharField(blank=True, max_length=60)),
                ("actual_ph", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("actual_pressure", models.CharField(blank=True, max_length=60)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("deviation", models.TextField(blank=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="step_executions", to="manufacturing.batch")),
                ("step", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="manufacturing.manufacturingstep")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="step_executions_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="step_executions_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("batch", "step__sequence"), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="manufacturingstepexecution",
            constraint=models.UniqueConstraint(fields=("batch", "step"), name="unique_step_execution_per_batch"),
        ),
        migrations.CreateModel(
            name="LineClearance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("DISPENSING", "Dispensación"),
                            ("MANUFACTURING", "Fabricación"),
                            ("FILLING", "Llenado"),
                            ("PACKAGING", "Acondicionamiento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=120)),
                ("production_line", models.CharField(blank=True, max_length=120)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("previous_product", models.CharField(blank=True, max_length=180)),
                ("previous_batch_code", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendiente"), ("APPROVED", "Aprobado"), ("REJECTED", "Rechazado")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verifier_signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/line-clearance/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_clearances", to="manufacturing.batch")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="line_clearances_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="line_clearances_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="LineClearanceCriterion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "criterion",
                    models.CharField(
                        choices=[
                            ("SANITATION", "Limpieza y sanitización"),
                            ("NO_OTHER_MATERIALS", "Ausencia de materiales de otros productos"),
                            ("EQUIPMENT_CONDITION", "Equipos en condiciones adecuadas"),
                            ("NO_OTHER_DOCUMENTS", "Ausencia de documentos de otra orden"),
                            ("NO_OTHER_LABELS", "Ausencia de etiquetas de otro producto"),
                            ("CURRENT_MATERIALS_IDENTIFIED", "Materiales actuales correctamente identificados"),
                            ("AREA_IDENTIFIED", "Área correctamente identificada"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        default="NOT_APPLICABLE",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/line-clearance/evidence/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("corrective_action", models.TextField(blank=True)),
                ("corrected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reinspection_result",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        max_length=20,
                    ),
                ),
                ("clearance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="manufacturing.lineclearance")),
                (
                    "corrective_action_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clearance_corrections", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="CleaningRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("record_type", models.CharField(choices=[("AREA", "Área limpia"), ("EQUIPMENT", "Equipo limpio")], max_length=20)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("equipment", models.CharField(blank=True, max_length=120)),
                ("equipment_code", models.CharField(blank=True, max_length=60)),
                ("cleaned_at", models.DateTimeField(blank=True, null=True)),
                ("previous_product", models.CharField(blank=True, max_length=180)),
                ("previous_batch_code", models.CharField(blank=True, max_length=60)),
                ("cleaning_method", models.TextField(blank=True)),
                ("sanitizer", models.CharField(blank=True, max_length=180)),
                ("sanitizer_concentration", models.CharField(blank=True, max_length=60)),
                ("sanitizer_batch", models.CharField(blank=True, max_length=60)),
                ("sanitizer_expires_at", models.DateField(blank=True, null=True)),
                ("result", models.CharField(blank=True, choices=[("APPROVED", "Aprobado"), ("REJECTED", "Rechazado")], max_length=20, null=True)),
                ("observations", models.TextField(blank=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cleaning_records", to="manufacturing.batch")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cleaning_records_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cleaning_records_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-cleaned_at", "-created_at"), "abstract": False},
        ),
        migrations.CreateModel(
            name="LineIdentification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("production_line", models.CharField(blank=True, max_length=120)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="line_identification", to="manufacturing.batch")),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="line_identifications_placed", to="employees.employee"
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="line_identifications_removed", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="ProductionControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lot_size", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("notes", models.TextField(blank=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="production_control", to="manufacturing.batch")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.unitofmeasure")),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="ProductionControlMaterial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("requested_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("delivered_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("returned_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("return_reason", models.TextField(blank=True)),
                ("additional_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("additional_reason", models.TextField(blank=True)),
                ("good_units", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("process_rejects", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("factory_rejects", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("observations", models.TextField(blank=True)),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="manufacturing.productioncontrol")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="production_control_lines", to="inventory.item")),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="production_materials_delivered", to="employees.employee"
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="production_materials_received", to="employees.employee"
                    ),
                ),
                (
                    "return_received_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="production_materials_return_received", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="FillingControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("production_line", models.CharField(blank=True, max_length=120)),
                ("equipment", models.CharField(blank=True, max_length=120)),
                ("source_tank", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("planned_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("produced_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("rejected_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("recovered_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("justification", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="filling_control", to="manufacturing.batch")),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filling_controls_as_responsible", to="employees.employee"
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filling_controls_as_verifier", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="FillingParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("activity", models.CharField(blank=True, max_length=180)),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/filling/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="manufacturing.fillingcontrol")),
                ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="employees.employee")),
            ],
            options={"ordering": ("created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="FillingLogEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("recorded_at", models.DateTimeField()),
                ("units_produced", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("displays", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("boxes", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("units_rejected", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("observations", models.TextField(blank=True)),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="log_entries", to="manufacturing.fillingcontrol")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filling_log_entries_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filling_log_entries_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("recorded_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="WeightVolumeControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("tare", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("lower_limit", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("upper_limit", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                (
                    "overall_result",
                    models.CharField(
                        choices=[("APPROVED", "Aprobado"), ("REJECTED", "Rechazado"), ("PENDING", "Pendiente")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="weight_volume_control", to="manufacturing.batch")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.unitofmeasure")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="weight_controls_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="weight_controls_verified", to="employees.employee"
                    ),
                ),
                (
                    "resumed_authorized_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="weight_controls_authorized_resume", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="WeightVolumeSample",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sample_number", models.PositiveSmallIntegerField()),
                ("sampled_at", models.DateTimeField(blank=True, null=True)),
                ("gross_weight", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("tare", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("volume", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        default="NOT_APPLICABLE",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("adjustment_made", models.TextField(blank=True)),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="samples", to="manufacturing.weightvolumecontrol")),
                (
                    "adjustment_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="weight_sample_adjustments", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("sample_number",), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="weightvolumesample",
            constraint=models.UniqueConstraint(fields=("control", "sample_number"), name="unique_weight_sample_number"),
        ),
        migrations.CreateModel(
            name="SealIntegrityControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("equipment", models.CharField(blank=True, max_length=120)),
                ("equipment_code", models.CharField(blank=True, max_length=60)),
                ("pressure_bar", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("time_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "overall_result",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("REPEAT", "Repetir ensayo"),
                            ("PENDING", "Pendiente"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seal_integrity_control", to="manufacturing.batch")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="seal_controls_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="seal_controls_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="SealIntegritySample",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sample_number", models.PositiveSmallIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CONFORMING", "Conforme"),
                            ("LEAK", "Fuga"),
                            ("DEFORMATION", "Deformación"),
                            ("RUPTURE", "Ruptura"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/seal-integrity/evidence/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="samples", to="manufacturing.sealintegritycontrol")),
            ],
            options={"ordering": ("sample_number",), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="sealintegritysample",
            constraint=models.UniqueConstraint(fields=("control", "sample_number"), name="unique_seal_sample_number"),
        ),
        migrations.CreateModel(
            name="PackagingControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "label_sample_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/packaging/label-sample/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("label_code", models.CharField(blank=True, max_length=80)),
                ("artwork_version", models.CharField(blank=True, max_length=40)),
                ("label_material_batch", models.CharField(blank=True, max_length=60)),
                (
                    "label_result",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        max_length=20,
                    ),
                ),
                ("label_observations", models.TextField(blank=True)),
                ("units_per_display", models.PositiveIntegerField(blank=True, null=True)),
                ("displays_per_box", models.PositiveIntegerField(blank=True, null=True)),
                ("units_per_box", models.PositiveIntegerField(blank=True, null=True)),
                ("complete_boxes", models.PositiveIntegerField(default=0)),
                ("incomplete_displays", models.PositiveIntegerField(default=0)),
                ("loose_units", models.PositiveIntegerField(default=0)),
                ("total_reconciled", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("balances", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("rejections", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("rejection_reasons", models.TextField(blank=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="packaging_control", to="manufacturing.batch")),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packaging_controls_as_responsible", to="employees.employee"
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packaging_controls_as_verifier", to="employees.employee"
                    ),
                ),
                (
                    "label_performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packaging_label_performed", to="employees.employee"
                    ),
                ),
                (
                    "label_verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="packaging_label_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="BatchLotMarking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("stage", models.CharField(choices=[("INITIAL", "Loteado inicial"), ("FINAL", "Loteado final")], max_length=20)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/packaging/lot-marking/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("printed_batch_code", models.CharField(blank=True, max_length=60)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("is_legible", models.BooleanField(blank=True, null=True)),
                ("is_correctly_placed", models.BooleanField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        max_length=20,
                    ),
                ),
                ("packaging_control", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lot_markings", to="manufacturing.packagingcontrol")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lot_markings_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lot_markings_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("stage", "created_at"), "abstract": False},
        ),
        migrations.CreateModel(
            name="AnalysisCertificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("manufactured_at", models.DateField(blank=True, null=True)),
                ("sampled_at", models.DateField(blank=True, null=True)),
                ("analyzed_at", models.DateField(blank=True, null=True)),
                (
                    "concept",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("QUARANTINE", "Cuarentena"),
                            ("REANALYSIS", "Reanálisis"),
                        ],
                        default="QUARANTINE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_certificate", to="manufacturing.batch")),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analysis_certificates_analyzed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analysis_certificates_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="AnalysisTestResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("result_type", models.CharField(blank=True, max_length=40)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("specification", models.CharField(blank=True, max_length=255)),
                ("lower_limit", models.CharField(blank=True, max_length=60)),
                ("upper_limit", models.CharField(blank=True, max_length=60)),
                ("method", models.CharField(blank=True, max_length=180)),
                ("equipment", models.CharField(blank=True, max_length=120)),
                ("equipment_parameters", models.CharField(blank=True, max_length=255)),
                ("bulk_result", models.CharField(blank=True, max_length=120)),
                ("finished_product_result", models.CharField(blank=True, max_length=120)),
                ("complies", models.BooleanField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("certificate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tests", to="manufacturing.analysiscertificate")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analysis_tests_performed", to="employees.employee"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analysis_tests_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="MicrobiologyAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sample_code", models.CharField(blank=True, max_length=80)),
                ("sample_type", models.CharField(blank=True, max_length=120)),
                ("taken_at", models.DateField(blank=True, null=True)),
                ("sent_at", models.DateField(blank=True, null=True)),
                ("laboratory", models.CharField(blank=True, max_length=180)),
                ("report_number", models.CharField(blank=True, max_length=80)),
                ("results", models.JSONField(blank=True, default=list)),
                ("specifications", models.JSONField(blank=True, default=list)),
                (
                    "overall_result",
                    models.CharField(
                        choices=[("APPROVED", "Aprobado"), ("REJECTED", "Rechazado"), ("PENDING", "Pendiente")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/microbiology/reports/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("approved_at", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="microbiology_analysis", to="manufacturing.batch")),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="microbiology_samples_taken", to="employees.employee"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="microbiology_approved", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "verbose_name_plural": "microbiology analyses", "abstract": False},
        ),
        migrations.CreateModel(
            name="DocumentChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "document_code",
                    models.CharField(
                        choices=[
                            ("PRODUCTION_CONTROL", "Control de producción"),
                            ("LINE_CLEARANCE", "Despeje de línea de áreas y equipos"),
                            ("CLEAN_AREA_EQUIPMENT", "Área y equipo limpio"),
                            ("DISPENSING_ORDER", "Orden de dispensación y fabricación"),
                            ("RAW_MATERIAL_IDENTIFICATION", "Identificación de materia prima dispensada"),
                            ("ANALYSIS_CERTIFICATE", "Certificado de análisis de producto a granel y terminado"),
                            ("MICROBIOLOGY", "Análisis microbiológico"),
                            ("LINE_IDENTIFICATION", "Identificación de línea"),
                            ("FILLING_CONTROL", "Control de llenado"),
                            ("RELEASE", "Liberación de producto terminado"),
                            ("PACKAGING_CONTROL", "Control de acondicionamiento"),
                            ("SEAL_INTEGRITY", "Control de hermeticidad"),
                            ("WEIGHT_VOLUME", "Control de peso o volumen"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("format_code", models.CharField(blank=True, max_length=40)),
                ("format_version", models.CharField(blank=True, max_length=20)),
                ("applies", models.BooleanField(default=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("YES", "Sí / Cumple"), ("NO", "No / No cumple"), ("NOT_APPLICABLE", "No aplica")],
                        default="NOT_APPLICABLE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En proceso"),
                            ("FILLED", "Diligenciado"),
                            ("REVIEWED", "Revisado"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "generated_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/document-checklist/generated/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("blocks_release", models.BooleanField(default=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_checklist", to="manufacturing.batch")),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_checklist_responsible", to="employees.employee"
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_checklist_verified", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("batch", "document_code"), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="documentchecklistitem",
            constraint=models.UniqueConstraint(fields=("batch", "document_code"), name="unique_document_checklist_item_per_batch"),
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("document_code", models.CharField(blank=True, max_length=40)),
                (
                    "file",
                    models.FileField(
                        upload_to="manufacturing/attachments/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg", "doc", "docx"))],
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="manufacturing.batch")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="BatchRelease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("released_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("retained_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("rejected_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("RELEASED", "Liberado"),
                            ("CONDITIONAL", "Liberado condicional"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="CONDITIONAL",
                        max_length=20,
                    ),
                ),
                (
                    "quality_signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/release/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                (
                    "technical_director_signature",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/release/signatures/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "release_document",
                    models.FileField(
                        blank=True, null=True, upload_to="manufacturing/release/documents/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("pdf", "png", "jpg", "jpeg"))],
                    ),
                ),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="release", to="manufacturing.batch")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.unitofmeasure")),
                ("warehouse_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.location")),
                (
                    "released_by_quality",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="releases_by_quality", to="employees.employee"
                    ),
                ),
                (
                    "approved_by_technical_director",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="releases_approved_technical_director", to="employees.employee"
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="BatchExport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("kind", models.CharField(choices=[("FULL_DOSSIER", "Expediente completo"), ("SINGLE_DOCUMENT", "Documento individual")], max_length=20)),
                ("document_code", models.CharField(blank=True, max_length=40)),
                ("include_attachments", models.BooleanField(default=True)),
                ("include_photos", models.BooleanField(default=True)),
                ("include_not_applicable", models.BooleanField(default=False)),
                ("file", models.FileField(upload_to="manufacturing/exports/")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exports", to="manufacturing.batch")),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
    ]
