# Generated by Django 5.2.3 on 2026-07-17 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0002_batch_expediente_completo"),
        ("inventory", "0004_alter_stock_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="specification", to="inventory.item")),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
        migrations.CreateModel(
            name="ProductSpecificationTest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("PHYSICOCHEMICAL", "Fisicoquímico"), ("MICROBIOLOGICAL", "Microbiológico")],
                        default="PHYSICOCHEMICAL",
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("specification_text", models.CharField(blank=True, max_length=255)),
                ("lower_limit", models.CharField(blank=True, max_length=60)),
                ("upper_limit", models.CharField(blank=True, max_length=60)),
                ("method", models.CharField(blank=True, max_length=180)),
                ("equipment", models.CharField(blank=True, max_length=120)),
                ("equipment_parameters", models.CharField(blank=True, max_length=255)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("specification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tests", to="manufacturing.productspecification")),
            ],
            options={"ordering": ("specification", "category", "sequence"), "abstract": False},
        ),
        migrations.AddConstraint(
            model_name="productspecificationtest",
            constraint=models.UniqueConstraint(fields=("specification", "category", "sequence"), name="unique_spec_test_sequence"),
        ),
    ]
