# Generated by Django 5.2.3 on 2026-07-23 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manufacturing', '0004_area_production_line_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='manufacturing/signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))])),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('RESPONSIBLE', 'Responsable'), ('VERIFIER', 'Verificador')], default='RESPONSIBLE', max_length=20)),
                ('signature_type', models.CharField(choices=[('DRAWN', 'Dibujada'), ('UPLOADED', 'Cargada')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=64)),
                ('document_status_at_signing', models.CharField(blank=True, max_length=60)),
                ('observation', models.TextField(blank=True)),
                ('replaced_reason', models.TextField(blank=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_signatures', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='manufacturing.signature')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='manufacturi_content_09ca85_idx')],
            },
        ),
    ]
