# Generated by Django 5.2.3 on 2026-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_signature_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrecord',
            name='phase',
            field=models.CharField(blank=True, choices=[('DISPENSING', 'Dispensación'), ('MANUFACTURING', 'Fabricación'), ('FILLING', 'Llenado'), ('PACKAGING', 'Acondicionamiento')], max_length=20),
        ),
    ]
