# Generated by Django 5.2.3 on 2026-07-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_cleaningrecord_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlotmarking',
            options={'ordering': ('created_at',)},
        ),
    ]
