# Generated by Codex on 2026-07-31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_alter_batchlotmarking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialidentificationprint',
            name='label_photo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='manufacturing/dispensing/label-photo/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg'))],
            ),
        ),
    ]
