# Generated by Django 5.2.3 on 2026-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_signature_updated_at'),
        ('manufacturing', '0007_alter_batchlotmarking_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lineclearance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'APPROVED'))), fields=('batch', 'phase'), name='unique_active_line_clearance_per_phase'),
        ),
    ]
