# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_raw_material_identification_label_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealintegritycontrol',
            name='overall_result',
            field=models.CharField(
                choices=[
                    ('APPROVED', 'Aprobado'),
                    ('REJECTED', 'Rechazado'),
                    ('REPEAT', 'Repetir ensayo'),
                    ('PENDING', 'Pendiente'),
                    ('NOT_APPLICABLE', 'No aplica'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
