# Generated by Codex on 2026-07-31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_signature_updated_at'),
        ('manufacturing', '0009_seal_integrity_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncontrol',
            name='warehouse_signature',
            field=models.FileField(
                blank=True, null=True, upload_to='manufacturing/production-control/signatures/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))],
            ),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='warehouse_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_controls_warehouse_signed', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='responsible_signature',
            field=models.FileField(
                blank=True, null=True, upload_to='manufacturing/production-control/signatures/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))],
            ),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='responsible_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_controls_responsible_signed', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='quality_signature',
            field=models.FileField(
                blank=True, null=True, upload_to='manufacturing/production-control/signatures/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))],
            ),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='quality_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_controls_quality_signed', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='leader_signature',
            field=models.FileField(
                blank=True, null=True, upload_to='manufacturing/production-control/signatures/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))],
            ),
        ),
        migrations.AddField(
            model_name='productioncontrol',
            name='leader_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_controls_leader_signed', to='employees.employee'),
        ),
    ]
