# Generated by Django 5.2.3 on 2026-06-11 00:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_cart_options_and_more'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Emitida'), ('VOIDED', 'Anulada')], default='ISSUED', max_length=20)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('customer_name', models.CharField(max_length=240)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_document', models.CharField(max_length=80)),
                ('billing_address', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='finance.financialtransaction')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='commerce.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='commerce.payment')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.salesinvoice')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
