# Generated by Django 5.2.3 on 2026-06-23 04:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salesinvoice_salesinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_resolution',
            field=models.CharField(blank=True, help_text='Texto de la resolución de facturación DIAN vigente al momento de emisión.', max_length=240),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5),
        ),
    ]
