# Generated by Django 5.2.3 on 2026-06-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_salesinvoice_dian_resolution_salesinvoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cufe',
            field=models.CharField(blank=True, editable=False, help_text='Código único de verificación de la factura, usado como contenido del QR.', max_length=96, unique=True),
        ),
    ]
