# Generated by Django 5.2.3 on 2026-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_salesinvoiceline_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
