# Generated by Django 5.2.3 on 2026-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_salesinvoice_customer_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_cufe',
            field=models.CharField(blank=True, help_text='CUFE real devuelto por Factus tras la validación ante la DIAN.', max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_qr_url',
            field=models.URLField(blank=True, help_text='URL de verificación oficial devuelta por Factus para el QR.', max_length=500),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de validación DIAN'), ('VALIDATED', 'Validada por la DIAN'), ('FAILED', 'Rechazada por la DIAN')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dian_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='factus_invoice_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='factus_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cufe',
            field=models.CharField(blank=True, editable=False, help_text='Hash local de referencia. No es un CUFE oficial DIAN, ver dian_cufe.', max_length=96, unique=True),
        ),
    ]
