# Generated by Django 5.2.3 on 2026-07-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_presentation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.TextField(),
        ),
    ]
