# Generated by Django 5.2.3 on 2026-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
