# Generated by Django 5.2.3 on 2026-07-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productvariant_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['presentation_number', 'sku']},
        ),
    ]
