# Generated by Django 5.2.3 on 2026-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_branch_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
