# Generated by Django 5.2.3 on 2026-07-06 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, upload_to='employees/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='document',
            field=models.FileField(blank=True, upload_to='employees/contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'))]),
        ),
    ]
