# Generated by Django 5.2.3 on 2026-07-17 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.FileField(blank=True, upload_to='employees/signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
    ]
