# Generated by Codex on 2026-07-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_signature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="access_password",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="employee",
            name="access_password_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="access_password_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_employee_access_passwords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
