# Generated by Codex on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_employee_access_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="signature_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
