# Generated by Django 5.2.3 on 2026-06-10 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('environment', models.CharField(max_length=20)),
                ('event_timestamp', models.BigIntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('transaction_status', models.CharField(blank=True, max_length=30)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAYMENT_PENDING', 'En pago'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CONFIRMED', 'Confirmado'), ('PROCESSING', 'En preparación'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAYMENT_PENDING', 'En pago'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CONFIRMED', 'Confirmado'), ('PROCESSING', 'En preparación'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('amount_in_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('ERROR', 'Error'), ('VOIDED', 'Anulado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
