# Generated by Django 5.2.3 on 2026-06-11 00:36

from django.db import migrations, models
from django.utils import timezone


def consolidate_active_carts(apps, schema_editor):
    Cart = apps.get_model("commerce", "Cart")
    CartItem = apps.get_model("commerce", "CartItem")
    customer_ids = (
        Cart.objects.filter(checked_out_at__isnull=True, deleted_at__isnull=True)
        .values_list("customer_id", flat=True)
        .distinct()
    )
    for customer_id in customer_ids:
        carts = list(
            Cart.objects.filter(
                customer_id=customer_id,
                checked_out_at__isnull=True,
                deleted_at__isnull=True,
            ).order_by("-updated_at", "-created_at")
        )
        if len(carts) < 2:
            continue
        target = carts[0]
        for source in carts[1:]:
            for item in CartItem.objects.filter(cart_id=source.id):
                target_item = CartItem.objects.filter(
                    cart_id=target.id,
                    variant_id=item.variant_id,
                ).first()
                if target_item:
                    target_item.quantity += item.quantity
                    target_item.save(update_fields=("quantity", "updated_at"))
                    item.delete()
                else:
                    item.cart_id = target.id
                    item.save(update_fields=("cart_id", "updated_at"))
            source.checked_out_at = timezone.now()
            source.save(update_fields=("checked_out_at", "updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_paymentwebhookevent_order_fulfillment_location_and_more'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='wompi_transaction_id',
            new_name='provider_transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MOCK', 'Simulado'), ('WOMPI', 'Wompi')], default='WOMPI', max_length=20),
        ),
        migrations.RunPython(consolidate_active_carts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('checked_out_at__isnull', True), ('deleted_at__isnull', True)), fields=('customer',), name='unique_active_cart_per_customer'),
        ),
    ]
