# Generated by Django 5.2.3 on 2026-06-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restored_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_orders', to='commerce.cart'),
        ),
    ]
