-- ============================================================
-- Database Seeds - Juhnios Rold
-- Test password for all users: Admin123!
-- ============================================================

INSERT INTO users
  (id, name, email, password_hash, first_name, last_name, phone, role, is_active, company_name, tax_id)
VALUES
  (uuid_generate_v4(), 'Admin Principal', 'admin@juhnios.com', '$2a$12$rC8CBnjiwC/F4SDzENGyGOJLY5Covo3hPwnK8MACLT95UtH.hJbB6', 'Admin', 'Principal', '3001234567', 'ADMIN', true, 'Juhnios Rold', '900123456-1'),
  (uuid_generate_v4(), 'Carlos Vendedor', 'vendedor@juhnios.com', '$2a$12$rC8CBnjiwC/F4SDzENGyGOJLY5Covo3hPwnK8MACLT95UtH.hJbB6', 'Carlos', 'Vendedor', '3009876543', 'SELLER', true, null, null),
  (uuid_generate_v4(), 'Ana Distribuidora', 'distribuidor@juhnios.com', '$2a$12$rC8CBnjiwC/F4SDzENGyGOJLY5Covo3hPwnK8MACLT95UtH.hJbB6', 'Ana', 'Distribuidora', '3005551234', 'DISTRIBUTOR', true, 'Distribuciones Ana', '901222333-4'),
  (uuid_generate_v4(), 'Maria Gonzalez', 'cliente@test.com', '$2a$12$rC8CBnjiwC/F4SDzENGyGOJLY5Covo3hPwnK8MACLT95UtH.hJbB6', 'Maria', 'Gonzalez', '3001112222', 'CLIENT', true, null, null)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  phone = EXCLUDED.phone,
  role = EXCLUDED.role,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

INSERT INTO products
  (id, name, slug, description, short_description, category, type, presentation,
   price, wholesale_price, pro_price, stock, min_stock, location, lot, sku,
   image_url, images, ingredients, benefits, how_to_use, weight_ml,
   active, featured, is_active, is_featured, tags)
VALUES
  (
    uuid_generate_v4(),
    'Aceite de Romero y Argan',
    'aceite-romero-argan',
    'Estimula el crecimiento capilar con una formula concentrada de romero y aceite de argan.',
    'Estimula crecimiento y fortalece desde la raiz',
    'aceites',
    'Aceite',
    '120ml',
    28900,
    24565,
    24565,
    45,
    10,
    'Bodega Principal',
    'L001',
    'JR-ACE-001',
    'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&q=80',
    '["https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&q=80"]',
    ARRAY['Aceite de Romero', 'Aceite de Argan', 'Vitamina E', 'Extracto de Biotina'],
    ARRAY['Estimula el crecimiento capilar', 'Reduce la caida del cabello', 'Brillo intenso'],
    'Aplica 5 a 8 gotas en el cuero cabelludo, masajea y deja actuar 30 minutos.',
    120,
    true,
    true,
    true,
    true,
    ARRAY['bestseller', 'capilar', 'crecimiento', 'aceite']
  ),
  (
    uuid_generate_v4(),
    'Silicona de Lino y Keratina',
    'silicona-lino-keratina',
    'Sella la cuticula capilar con aceite de lino y keratina hidrolizada para brillo y control de frizz.',
    'Brillo espejo y control del frizz',
    'siliconas',
    'Silicona',
    '50ml',
    24900,
    21165,
    21165,
    38,
    15,
    'Bodega Principal',
    'L002',
    'JR-SIL-001',
    'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=80',
    '["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=80"]',
    ARRAY['Aceite de Lino', 'Keratina Hidrolizada', 'Pantenol'],
    ARRAY['Control del frizz', 'Brillo intenso', 'Suavidad extrema'],
    'Aplica una pequena cantidad de medios a puntas. No enjuagues.',
    50,
    true,
    true,
    true,
    true,
    ARRAY['bestseller', 'capilar', 'brillo', 'silicona']
  ),
  (
    uuid_generate_v4(),
    'Tratamiento Restaurador de Keratina',
    'tratamiento-restaurador-keratina',
    'Reconstruccion profunda con keratina para cabello danado por calor, quimicos y coloracion.',
    'Reconstruccion profunda para cabello danado',
    'tratamientos',
    'Tratamiento',
    '220g',
    38900,
    33065,
    33065,
    22,
    8,
    'Tienda',
    'L003',
    'JR-TRA-001',
    'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=800&q=80',
    '["https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=800&q=80"]',
    ARRAY['Keratina Natural', 'Proteina de Seda', 'Aceite de Ricino'],
    ARRAY['Reconstruccion profunda', 'Suavidad extrema', 'Brillo intenso'],
    'Aplica en cabello limpio y humedo. Deja actuar 20 minutos y enjuaga.',
    220,
    true,
    true,
    true,
    true,
    ARRAY['tratamiento', 'keratina', 'reconstruccion']
  ),
  (
    uuid_generate_v4(),
    'Crema Corporal de Manteca de Karite',
    'crema-corporal-manteca-karite',
    'Hidratacion corporal de 24 horas con manteca de karite y aceite de coco.',
    'Hidratacion 24h con manteca de karite',
    'corporal',
    'Crema',
    '300ml',
    32900,
    27965,
    27965,
    30,
    12,
    'Bodega Principal',
    'L004',
    'JR-COR-001',
    'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80',
    '["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80"]',
    ARRAY['Manteca de Karite', 'Aceite de Coco', 'Aloe Vera'],
    ARRAY['Hidratacion 24 horas', 'Piel suave', 'Aroma duradero'],
    'Aplica sobre piel limpia despues del bano.',
    300,
    true,
    false,
    true,
    false,
    ARRAY['corporal', 'hidratacion', 'karite']
  ),
  (
    uuid_generate_v4(),
    'Linea Baby Suave Shampoo',
    'baby-suave-shampoo',
    'Shampoo sin lagrimas, sulfatos ni parabenos para bebes y ninos con piel sensible.',
    'Sin lagrimas ni sulfatos para bebes',
    'baby',
    'Shampoo',
    '200ml',
    22900,
    19465,
    19465,
    50,
    15,
    'Bodega Principal',
    'L005',
    'JR-BAB-001',
    'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80',
    '["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80"]',
    ARRAY['Extracto de Manzanilla', 'Aceite de Lavanda', 'Aloe Vera'],
    ARRAY['Sin lagrimas', 'Hipoalergenico', 'Suavidad extrema'],
    'Aplica sobre cabello humedo, masajea suavemente y enjuaga.',
    200,
    true,
    false,
    true,
    false,
    ARRAY['baby', 'ninos', 'suave', 'shampoo']
  )
ON CONFLICT (slug) DO UPDATE SET
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  category = EXCLUDED.category,
  type = EXCLUDED.type,
  presentation = EXCLUDED.presentation,
  price = EXCLUDED.price,
  wholesale_price = EXCLUDED.wholesale_price,
  pro_price = EXCLUDED.pro_price,
  stock = EXCLUDED.stock,
  min_stock = EXCLUDED.min_stock,
  location = EXCLUDED.location,
  lot = EXCLUDED.lot,
  sku = EXCLUDED.sku,
  image_url = EXCLUDED.image_url,
  images = EXCLUDED.images,
  ingredients = EXCLUDED.ingredients,
  benefits = EXCLUDED.benefits,
  active = EXCLUDED.active,
  featured = EXCLUDED.featured,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  updated_at = NOW();
