# Generated by Django 5.2.3 on 2026-06-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_purchase_mode_wholesale_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_id_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_id_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_id_type_other',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_international_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
