# Generated by Django 5.2.3 on 2026-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_update_shipping_defaults_and_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='10.98833', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='-74.79750', max_digits=9, null=True),
        ),
    ]
