# Generated by Django 5.2.3 on 2026-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_access_control'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolecomponentpermission',
            constraint=models.UniqueConstraint(fields=('role', 'component'), name='identity_role_component_permission_unique'),
        ),
    ]
