# Generated by Codex on 2026-06-19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_rolecomponentpermission_identity_role_component_permission_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("registration_data", models.JSONField(default=dict)),
                ("password_hash", models.CharField(max_length=128)),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("sent_count", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
