# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="previous_code_hashes",
            field=models.JSONField(default=list),
        ),
    ]
