# Generated by Codex on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_sync_manufacturing_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_view_loan_requests",
            field=models.BooleanField(
                default=False,
                help_text="Acceso puntual a solicitudes de préstamo, independiente del rol asignado.",
            ),
        ),
    ]
