# Generated by Codex on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0012_sync_contabilidad_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles extra que se suman al principal (ej. Contabilidad), sin reemplazarlo.",
                related_name="users_with_additional_role",
                to="identity.role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                help_text="Rol principal: define la vista por defecto al iniciar sesión.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="identity.role",
            ),
        ),
    ]
