# Generated by Codex on 2026-08-18

from django.db import migrations

from apps.identity.access_control import COMPONENT_DEFINITIONS, build_default_role_permissions


def sync_seller_employee_self_service(apps, schema_editor):
    """Treat sellers as employees for self-service access.

    The SELLER role keeps its commercial permissions, and gains read-only access
    to ``employees.management`` so the employee portal/configuration flows work
    for sellers without exposing the full RRHH management module.
    """
    Role = apps.get_model("identity", "Role")
    Component = apps.get_model("identity", "Component")
    RoleComponentPermission = apps.get_model("identity", "RoleComponentPermission")

    component_by_code = {}
    for component_def in COMPONENT_DEFINITIONS:
        component, _ = Component.objects.update_or_create(
            code=component_def["code"],
            defaults={
                "name": component_def["name"],
                "description": component_def["description"],
                "is_active": True,
                "deleted_at": None,
            },
        )
        component_by_code[component.code] = component

    permissions_matrix = build_default_role_permissions()
    for role_code, component_permissions in permissions_matrix.items():
        role = Role.objects.filter(code=role_code).first()
        if not role:
            continue
        for component_code, permission_data in component_permissions.items():
            component = component_by_code.get(component_code)
            if not component:
                continue
            RoleComponentPermission.objects.update_or_create(
                role=role,
                component=component,
                defaults={
                    "can_view": permission_data.get("can_view", False),
                    "can_edit": permission_data.get("can_edit", False),
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0017_sync_company_documents_component"),
    ]

    operations = [
        migrations.RunPython(sync_seller_employee_self_service, migrations.RunPython.noop),
    ]
